//document.writeln("<script type=\'text/javascript\' src=\'js/user.js\' ></script>");
document.writeln("");
document.writeln("		<nav class=\'navbar navbar-default navbar-static-top\' style=\'background-color: #1e89e0;height: 60px;\' role=\'navigation\'>");
document.writeln("		 <div class=\'container-fluid\' style=\'width: 980px;\'>");
document.writeln("		    <div class=\'navbar-header\' >");
document.writeln("<a class=\'\' href=\'#\'><img src=\'img/logo.png\' style=\'width: 150px;height: 60px;float: left;\'/></a>");
document.writeln("		      <a class=\'navbar-brand\' href=\'homePage.html\' target=\'_top\'>首页</a>");
document.writeln("		      <a class=\'navbar-brand\' style=\'background-color: #006bc7;\' href=\'personal.html\'>我的订单</a>");
document.writeln("		      <a class=\'navbar-brand\' href=\'openStore.html\'>加盟合作</a>");
document.writeln("		    </div>");
document.writeln("		    <ul class=\'nav navbar-nav navbar-right\'\'>");
document.writeln("		      <li><a class=\'log-reg\' href=\'login.html\'> 登录/注册</a></li>");
document.writeln("		      <li class=\'dropdown ng-hide\'>");
document.writeln("			        <a href=\'#\' class=\'dropdown-toggle\' >");
document.writeln("			             未登录<b class=\'caret\'></b>");
document.writeln("			        </a>");
document.writeln("		                <ul class=\'dropdown-menu\'>");
document.writeln("		                    <li><a href=\'personal.html\'>个人中心</a></li>");
document.writeln("		                    <li><a href=\'address.html\'>我的地址</a></li>");
document.writeln("		                    <li><a href=\'favor.html\'>我的收藏</a></li>");
document.writeln("		                    <li class=\'divider\'></li>");
document.writeln("<li><a href=\'#\' onclick=\'logout()\'>退出登录</a></li>");
document.writeln("		                </ul>");
document.writeln("		      </li>");
document.writeln("		    </ul>");
document.writeln("		  </div>");
document.writeln("		</nav>");
document.writeln("");
document.writeln("");