document.writeln("<div style=\'float: left;\'>");
document.writeln("				<div class=\'orders-link-box\'>");
document.writeln("					<div class=\'link-group\'>");
document.writeln("						<p class=\'title\'><a href=\'personal.html\'>个人中心</a></p>");
document.writeln("						<p class=\'title\'>我的订单</p>");
document.writeln("						<ul class=\'link-ul\'>");
document.writeln("							<li><a href=\'order.html#status=-1\'>全部订单</a><i class=\'icon-right\'></i></li>");
document.writeln("							<li><a href=\'order.html#status=0\'>待付款</a><i class=\'icon-right\'></i></li>");
document.writeln("						    <li><a href=\'order.html#status=2\'>已完成</a><i class=\'icon-right\'></i></li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'link-group\'>");
document.writeln("						<p class=\'title\'><span>我的资料</span></p>");
document.writeln("						<ul class=\'link-ul\'>");
document.writeln("							<li><a href=\'info.html'>个人资料</a><i class=\'icon-right\'></i></li>");
document.writeln("							<li><a href=\'address.html\'>地址管理</a><i class=\'icon-right\'></i></li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'link-group\'>");
document.writeln("						<p class=\'title\'><span>我的评论</span></p>");
document.writeln("						<ul class=\'link-ul\'>");
document.writeln("							<li><a href=\'myComment.html#status=0'>待评价</a><i class=\'icon-right\'></i></li>");
document.writeln("							<li><a href=\'myComment.html#status=1\'>已评价</a><i class=\'icon-right\'></i></li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					<div class=\'link-group\'>");
document.writeln("						<p class=\'title\'><a href=\'apply.html'>商家申请</a></p>");
document.writeln("					</div>");
document.writeln("					<div class=\'link-group\'>");
document.writeln("						<p class=\'title\'><a href=\'favor.html' \'>我的收藏</a></p>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");