document.writeln("<nav class=\'navbar navbar-default navbar-static-top\' style=\'background-color: rgba(0,0,0,.4);height: 48px;\' role=\'navigation\'>");
document.writeln("		 <div class=\'container-fluid\' style=\'width: 980px;\'>");
document.writeln("		    <div class=\'navbar-header\'>");
document.writeln("		      <a class=\'navbar-brand\' href=\'#\' style=\'color: #FFF;font-size: 30px;\'>點一點</a>");
document.writeln("		      <a class=\'navbar-brand\' href=\'homePage.html\' style=\'color: #FFF;\'>首页</a>");
document.writeln("		      <a class=\'navbar-brand\' href=\'personal.html\' style=\'color: #FFF;\'>我的订单</a>");
document.writeln("		      <a class=\'navbar-brand\' href=\'openStore.html\' style=\'color: #FFF;\'>加盟合作</a>");
document.writeln("		    </div>");
document.writeln("		    <ul class=\'nav navbar-nav navbar-right\'\'>");
document.writeln("		      <li><a class=\'log-reg active\' href=\'login.html\' style=\'color: #FFF;\'> 登录/注册</a></li>");
document.writeln("		      <li class=\'dropdown ng-hide\'>");
document.writeln("		                <a href=\'#\' class=\'dropdown-toggle\' style=\'color: #FFF;\'>");
document.writeln("		                    admin <b class=\'caret\'></b>");
document.writeln("		                </a>");
document.writeln("		                <ul class=\'dropdown-menu\'>");
document.writeln("		                    <li><a href=\'personal.html\'>个人中心</a></li>");
document.writeln("		                    <li><a href=\'address.html\'>我的地址</a></li>");
document.writeln("		                    <li><a href=\'favor.html\'>我的收藏</a></li>");
document.writeln("		                    <li class=\'divider\'></li>");
document.writeln("<li><a href=\'#\' onclick=\'logout()\'>退出登录</a></li>");
document.writeln("		                </ul>");
document.writeln("		            </li>");
document.writeln("		    </ul>");
document.writeln("		  </div>");
document.writeln("		</nav>");
document.writeln("		<div class=\'main\'>");
document.writeln("			<div class=\'shopguide\'>");
document.writeln("				<div class=\'container\'>");
document.writeln("					<div class=\'shopguide-info\'>");
document.writeln("						<img src=\'' />");
document.writeln("						<div class=\'shopguide-info-wrapper\'>");
document.writeln("							<div><h1 class=\'ng-binding\'></h1></div>");
document.writeln("							<p class=\'shopguide-info-rate\'>");
document.writeln("								<!--<div class=\'starrating icon-star ng-isolate-scope\'>-->");
document.writeln("									<span class=\'star-ranking\'>");
document.writeln("            							<span class=\'star-score\' style=\'width: 50px\'></span>");
document.writeln("       								</span>");
document.writeln("								<!--</div>-->");
//document.writeln("								<span style=\'line-height: 15px;\'>(<a href=\'#\'>30</a>)</span>");
document.writeln("							</p>");
document.writeln("						</div>");
document.writeln("						<div class=\'shopguide-info-extra\'>");
document.writeln("							<ul>");
document.writeln("								<li class=\'shopguide-extra-item\'>商家地址： <span class=\'address\'>定远县定城镇城北村滩塘队</span></li>");
document.writeln("								<li class=\'shopguide-extra-item\'>营业时间： 10:00-23:55</li>");
document.writeln("								<li class=\'shopguide-extra-item\'>商家电话：<span class=\'contactPhone\'>0555014568</span></li>");
document.writeln("								<li class=\'shopguide-extra-item \'>用餐高峰时请提前下单</li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'shopguide-server\'>");
document.writeln("						<span ng-hide=\'shop.id == 656683\' class=\'\'><em>起送价</em> <em class=\'shopguide-server-value ng-binding\'>元</em></span>");
document.writeln("						<span>");
document.writeln("							<em>配送费</em>");
document.writeln("							<em class=\'shopguide-server-value ng-binding\'>元</em>");
document.writeln("						</span>");
document.writeln("						<span>");
document.writeln("							<em>平均到达速度</em>");
document.writeln("							<em class=\'shopguide-server-value ng-binding\'>分钟</em>");
document.writeln("						</span>");
document.writeln("					</div>");
document.writeln("					<a class=\'shopguide-favor\' href=\'javascript:\'>");
document.writeln("					<i class=\'icon-favorite ng-scope\'></i> ");
document.writeln("					<span ng-if=\'!isFavorShop\' class=\'isFavorShop ng-scope\'>收藏</span>");
document.writeln("				</a>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("			</div>");